services:
  api-blog:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-blog
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    mem_limit: 256m
    ports:
      - "8002:3000"
    networks:
      - blog-network
      - shared-network
    restart: always
  ui-blog:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge
  shared-network:
    external:
      name: database_shared-network
